### PR TITLE
Fixes the Institutions migration isssue

### LINKED ISSUE #36: Add Seed Data for the Institution
- Currently, we don't create any record for the `Institution` in the `seeds.rb` file and we are using it for the `Account` creation.
- Hence it gives the error during `rails db:seed`
- We need to create Inistition before  `Account` creation.

### PR DESCRIPTION
**Pull request by chahmedejaz**
Resolves #36 

- This PR fixes the migration failure due to the invalid GoCardless credentials by the following changes: 
  - Remove the migration in which we are creating the institutions and
  - Add rake task to sync all the GoCardless institutions in the app
  - Update the README about the newly added rake task

- It's been observed that we are _always_ having the **failing Github tests workflow**, that's because of the same issue. This PR will fix this workflow as well.

### CODE REVIEW

**Comment by EduardoSimon** [comment]
Thank you so much for your contribution @chahmedejaz! Merging it!

**Comment by EduardoSimon** [comment]
As an enhancement, we could add a parameter to the rake that provides the country from which we want to import institutions. However, that would probably mean that we need to change our data model and store that association as well.

**Comment by chahmedejaz** [comment]
> As an enhancement, we could add a parameter to the rake that provides the country from which we want to import institutions. However, that would probably mean that we need to change our data model and store that association as well.

Sure, @EduardoSimon. I'd love to work on it. It'd be great if you could create the issue for this with the AC. Thanks :)

**Comment by EduardoSimon** [comment]
Sorry what do you mean by AC?

**Comment by chahmedejaz** [comment]
> Sorry what do you mean by AC?

Sorry for the confusion. I meant the Acceptance Criteria of the fix for the issue you will create.

**Pull request merged**
